"use client";

import React, { useMemo, useState } from "react";
import {
  Card,
  CardHeader,
  CardBody,
  Accordion,
  AccordionItem,
  Chip,
  Divider,
  Tooltip,
  Button,
  Alert,
  useDisclosure,
} from "@heroui/react";
import { useRouter } from "next/navigation";
import AddScoreDialog from "./AddScoreDialog";
import { UserVotesResult } from "@/lib/types"; // added for userVotes typing
export type AiAnswer = {
  id: string;
  aiModel: string;
  confidenceScore?: number | null;
  isAccepted?: boolean | null;
  votes?: number | null;
  userHelpfulVotes?: number | null;
  userNotHelpfulVotes?: number | null;
  createdAt?: string | Date | null;
  questionId: string;
  accepted: boolean;
  votedByUserIds?: string[]; // NEW field tracking which users voted
  userId: string;
  hasVoted: boolean;
  // Structured fields from your JSON schema
  content?: string | null; // aka summary
  diagnosis?: string | null;
  likelyRootCause?: string | null;
  fixStepByStep?: string[] | string | null;
  codePatch?: string | null; // diff or snippet
  alternatives?: string[] | string | null;
  gotchas?: string[] | string | null;
  rawAiResponse?: string | null; // original JSON / text
};
type Props = {
  answers: AiAnswer[];
  defaultOpenKeys?: string[]; // optional list of Accordion keys to start open
  userId?: string; // current logged-in user id
  userVotes?: UserVotesResult[]; // optional votes passed from parent
};

/** Small copy-to-clipboard helper */
const CopyButton: React.FC<{ text?: string | null; label?: string }> = ({
  text,
  label = "Copy",
}) => {
  const [copied, setCopied] = useState(false);
  const canCopy = (text ?? "").length > 0;

  return (
    <Tooltip
      content={
        copied ? "Copied!" : canCopy ? "Copy to clipboard" : "Nothing to copy"
      }
    >
      <Button
        size="sm"
        variant="flat"
        isDisabled={!canCopy}
        onPress={async () => {
          if (!text) return;
          await navigator.clipboard.writeText(text);
          setCopied(true);
          setTimeout(() => setCopied(false), 1200);
        }}
      >
        {copied ? "Copied" : label}
      </Button>
    </Tooltip>
  );
};

const formatDate = (d?: string | Date | null) => {
  if (!d) return "—";
  const date = typeof d === "string" ? new Date(d) : d;
  if (Number.isNaN(date.getTime())) return "—";
  // dd/MM/yyyy like in your screenshot
  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

const normalizeLines = (val?: string[] | string | null) => {
  if (!val) return [];
  if (Array.isArray(val)) return val.filter(Boolean);
  return val
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);
};

// Per-answer alert (keeps its own visibility)
function ResultAlert({
  ans,
  userId,
  userVotes,
}: {
  ans: AiAnswer;
  userId?: string;
  userVotes?: UserVotesResult[];
}) {
  // Hooks must be called unconditionally at the top
  const { isOpen, onOpen, onClose } = useDisclosure();
  const router = useRouter();

  // Do not display any alert if there is no logged in user
  if (!userId) return null;

  const votes = ans.votes ?? 0;
  // get all user votes equal to this userId
  const userVoteRecords =
    userVotes?.filter((v) => v.userId === userId && v.aiId === ans.id) || [];
  console.log("User vote records for user", userId, ":", userVoteRecords);
  // UPDATED: broaden hasVoted detection to include ans.hasVoted and ans.votedByUserIds for fresh user sessions
  console.log("Checking votes for user:", userId, "on answer:", ans.id);
  console.log("Current user:", userId);
  const hasVoted = !!(
    userId && userVotes?.some((v) => v.aiId === ans.id && v.userId === userId)
  );

  if (votes === 0) {
    return (
      <div className="flex items-center justify-center w-full">
        <Alert
          color="warning"
          description="Could you please provide the result score?"
          endContent={
            !hasVoted ? (
              <AddScoreDialog
                questionId={ans.questionId}
                aiAnswerId={ans.id}
                initialVotes={ans.votes}
                initialHelpful={ans.userHelpfulVotes}
                initialNotHelpful={ans.userNotHelpfulVotes}
                model={ans.aiModel}
                userId={userId}
                existingVotedByUserIds={ans.votedByUserIds ?? []}
                onUpdated={() => router.refresh()}
              />
            ) : null
          }
          title={`This response was generated by ${
            ans.aiModel || " an AI model"
          }`}
          variant="faded"
        />
      </div>
    );
  }

  const title = ans.accepted
    ? "AI answer accepted"
    : "AI answer not yet accepted";
  const description = `Accepted: ${
    ans.accepted ? "Yes" : "No"
  } · Votes: ${votes}`;

  return (
    <>
      <Alert
        color="success"
        description={description}
        isVisible={true}
        title={title}
        variant="faded"
        endContent={
          !hasVoted ? (
            <Button size="sm" color="warning" variant="flat" onPress={onOpen}>
              Add Score
            </Button>
          ) : null
        }
      />
      {!hasVoted && (
        <AddScoreDialog
          questionId={ans.questionId}
          aiAnswerId={ans.id}
          initialVotes={ans.votes}
          initialHelpful={ans.userHelpfulVotes}
          initialNotHelpful={ans.userNotHelpfulVotes}
          model={ans.aiModel}
          isOpen={isOpen}
          onClose={() => {
            onClose();
            router.refresh();
          }}
          onUpdated={() => router.refresh()}
          userId={userId}
          existingVotedByUserIds={ans.votedByUserIds ?? []}
        />
      )}
    </>
  );
}
// Note: Accordion expects its direct children to be AccordionItem elements.
// Avoid wrapping AccordionItem in custom components, or re-export getCollectionNode.

export default function AiAnswerGroup({
  answers,
  defaultOpenKeys,
  userId,
  userVotes, // accepted and used by ResultAlert
}: Props) {
  console.log("UserVotes in AiAnswerGroup:", userVotes);
  const sorted = useMemo(
    () =>
      [...answers].sort((a, b) => {
        // Example sort: accepted first, then higher confidence, then most votes
        const aAccepted = a.accepted ? 1 : 0;
        const bAccepted = b.accepted ? 1 : 0;
        if (bAccepted - aAccepted !== 0) return bAccepted - aAccepted;
        const aConf = a.confidenceScore ?? 0;
        const bConf = b.confidenceScore ?? 0;
        if (bConf - aConf !== 0) return bConf - aConf;
        return (b.votes ?? 0) - (a.votes ?? 0);
      }),
    [answers]
  );

  return (
    <div className="flex flex-col gap-6 border-b pb-3 px-6">
      {sorted.map((ans) => {
        // Keep arrays as arrays, but if a string is provided, we will render as raw HTML below
        const steps = Array.isArray(ans.fixStepByStep)
          ? (ans.fixStepByStep as string[]).filter(Boolean)
          : normalizeLines(ans.fixStepByStep);
        const stepsHtml: string | null =
          typeof ans.fixStepByStep === "string"
            ? (ans.fixStepByStep as string)
            : null;

        const alternatives = Array.isArray(ans.alternatives)
          ? (ans.alternatives as string[]).filter(Boolean)
          : normalizeLines(ans.alternatives);
        const alternativesHtml: string | null =
          typeof ans.alternatives === "string"
            ? (ans.alternatives as string)
            : null;

        const gotchas = Array.isArray(ans.gotchas)
          ? (ans.gotchas as string[]).filter(Boolean)
          : normalizeLines(ans.gotchas);
        const gotchasHtml: string | null =
          typeof ans.gotchas === "string" ? (ans.gotchas as string) : null;

        return (
          <Card
            key={ans.id}
            shadow="sm"
            className="border border-default-200 rounded-2xl mt-2 overflow-hidden"
          >
            <CardHeader className="bg-primary-200/60 dark:bg-primary-300/30 gap-4 flex-wrap">
              <div className="flex flex-wrap items-center gap-x-6 gap-y-2 w-full">
                <div className="flex items-center gap-2">
                  <span className="font-medium">AI Model:</span>
                  <Chip color="primary" variant="flat">
                    {ans.aiModel || "—"}
                  </Chip>
                </div>

                <div className="flex items-center gap-2">
                  <span className="font-medium">AI Score:</span>
                  <span>
                    {ans.confidenceScore != null
                      ? ans.confidenceScore.toFixed(2)
                      : "—"}
                  </span>
                </div>

                <div className="flex items-center gap-2">
                  <span className="font-medium">Is Accepted:</span>
                  <Chip
                    color={ans.accepted ? "success" : "default"}
                    variant="flat"
                  >
                    {ans.accepted ? "Yes" : "No"}
                  </Chip>
                </div>

                <div className="flex items-center gap-2">
                  <span className="font-medium">Votes:</span>
                  <span>{ans.votes ?? 0}</span>
                </div>

                <div className="ml-auto flex items-center gap-2">
                  <span className="font-medium">Date :</span>
                  <span>{formatDate(ans.createdAt)}</span>
                </div>
              </div>
              {/* Conditional alert row */}
              <div className="w-full mt-2">
                <ResultAlert ans={ans} userId={userId} userVotes={userVotes} />
              </div>
            </CardHeader>

            <CardBody className="p-0">
              <Accordion
                isCompact
                variant="light"
                selectionMode="multiple"
                defaultExpandedKeys={defaultOpenKeys}
                className="p-4 flex flex-col gap-3"
              >
                <AccordionItem
                  key="results"
                  aria-label="Results"
                  title="Results"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2 ",
                  }}
                >
                  <div className="pl-2 max-h-[60vh] overflow-auto">
                    {/** Compact content: collapse multiple newlines and reduce default element margins */}
                    {(() => {
                      const compactContent = (ans.content ?? "—").replace(
                        /(\n\s*){2,}/g,
                        "\n"
                      );
                      return (
                        <div
                          className="max-w-full w-full text-default-800 dark:text-default-600 break-words whitespace-pre-wrap overflow-x-auto leading-relaxed text-sm [&_p]:my-1 [&_ul]:my-2 [&_ol]:my-2 [&_h1]:mt-4 [&_h1]:mb-2 [&_h2]:mt-3 [&_h2]:mb-2 [&_h3]:mt-2 [&_h3]:mb-1 [&_pre]:my-2 [&_pre]:p-3 [&_pre]:rounded-md [&_pre]:bg-default-100 [&_p+pre]:mt-2 [&_li]:my-0.5 [&_code]:break-words"
                          style={{ wordBreak: "break-word" }}
                          dangerouslySetInnerHTML={{ __html: compactContent }}
                        />
                      );
                    })()}
                  </div>
                </AccordionItem>

                <AccordionItem
                  key="diagnosis"
                  aria-label="Diagnosis"
                  title="Diagnosis"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  <div
                    className="pl-2"
                    dangerouslySetInnerHTML={{ __html: ans.diagnosis ?? "—" }}
                  />
                </AccordionItem>

                <AccordionItem
                  key="root-cause"
                  aria-label="Likely root cause"
                  title="Likely root cause"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  <div
                    className="pl-2"
                    dangerouslySetInnerHTML={{
                      __html: ans.likelyRootCause ?? "—",
                    }}
                  />
                </AccordionItem>

                <AccordionItem
                  key="fix-steps"
                  aria-label="Fix (step-by-step)"
                  title="Fix (step-by-step)"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  {stepsHtml ? (
                    <div
                      className="pl-2"
                      dangerouslySetInnerHTML={{ __html: stepsHtml }}
                    />
                  ) : steps.length ? (
                    <ol className="list-decimal pl-5 space-y-1">
                      {steps.map((s, i) => (
                        <li key={i} dangerouslySetInnerHTML={{ __html: s }} />
                      ))}
                    </ol>
                  ) : (
                    <div className="pl-2">—</div>
                  )}
                </AccordionItem>

                <AccordionItem
                  key="code-patch"
                  aria-label="Code patch"
                  title="Code patch"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  <div className="flex flex-col gap-3 pl-2">
                    <div className="relative rounded-xl overflow-hidden bg-default-50 ring-1 ring-default-200">
                      <div
                        className="overflow-x-auto p-4 text-sm leading-relaxed"
                        dangerouslySetInnerHTML={{
                          __html: ans.codePatch ?? "—",
                        }}
                      />
                    </div>
                    <div className="flex gap-2">
                      <CopyButton text={ans.codePatch} />
                    </div>
                  </div>
                </AccordionItem>

                <AccordionItem
                  key="alternatives"
                  aria-label="Alternatives"
                  title="Alternatives"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  {alternativesHtml ? (
                    <div
                      className="pl-2"
                      dangerouslySetInnerHTML={{ __html: alternativesHtml }}
                    />
                  ) : alternatives.length ? (
                    <ul className="list-disc pl-5 space-y-1">
                      {alternatives.map((s, i) => (
                        <li key={i} dangerouslySetInnerHTML={{ __html: s }} />
                      ))}
                    </ul>
                  ) : (
                    <div className="pl-2">—</div>
                  )}
                </AccordionItem>

                <AccordionItem
                  key="gotchas"
                  aria-label="Gotchas"
                  title="Gotchas"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  {gotchasHtml ? (
                    <div
                      className="pl-2 prose prose-sm max-w-none whitespace-pre-wrap leading-relaxed dark:text-default-600"
                      dangerouslySetInnerHTML={{ __html: gotchasHtml }}
                    />
                  ) : gotchas.length ? (
                    <ul className="list-disc pl-5 space-y-1">
                      {gotchas.map((s, i) => (
                        <li key={i} dangerouslySetInnerHTML={{ __html: s }} />
                      ))}
                    </ul>
                  ) : (
                    <div className="pl-2">—</div>
                  )}
                </AccordionItem>

                <AccordionItem
                  key="raw"
                  aria-label="Raw Ai Response"
                  title="Raw Ai Response"
                  subtitle={
                    <span className="text-default-500 ml-2">
                      Press to expand
                    </span>
                  }
                  classNames={{
                    base: "bg-default-100 rounded-xl",
                    title: "text-base font-medium ml-2",
                    content: "pt-2",
                  }}
                >
                  <div className="flex flex-col gap-3 pl-2">
                    <div className="relative rounded-xl overflow-hidden bg-default-50 ring-1 ring-default-200 w-full">
                      <div className="p-4 text-sm leading-relaxed overflow-auto max-h-96">
                        <pre className="whitespace-pre-wrap break-all w-full min-w-0 overflow-hidden">
                          <code className="break-all word-break-all">
                            {ans.rawAiResponse}
                          </code>
                        </pre>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <CopyButton text={ans.rawAiResponse} />
                    </div>
                  </div>
                </AccordionItem>
              </Accordion>

              <Divider />
            </CardBody>
          </Card>
        );
      })}
    </div>
  );
}
