// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestionService.Data;

#nullable disable

namespace QuestionService.Data
{
    [DbContext(typeof(QuestionDbContext))]
    [Migration("20251121130039_RoleAdded")]
    partial class RoleAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionService.Models.AIModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AIModels");

                    b.HasData(
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OpenAI GPT-5 model.",
                            Name = "gpt-5-chat",
                            Version = "5.0"
                        },
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Google Gemini 2.5 Flash model.",
                            Name = "gemini-2.5-flash",
                            Version = "2.5"
                        },
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OpenAI GPT-OSS-120B open source model.",
                            Name = "openai/gpt-oss-120b",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Meta Llama 4 Maverick 17B Instruct model.",
                            Name = "meta-llama/llama-4-maverick-17b-128e-instruct",
                            Version = "4.0"
                        },
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a005",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Alibaba Qwen 3 32B model.",
                            Name = "qwen/qwen3-32b",
                            Version = "3.0"
                        },
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OpenAI GPT-4.1 model.",
                            Name = "gpt-4.1",
                            Version = "4.1"
                        },
                        new
                        {
                            Id = "a1f1e941-3d7e-4f07-ab43-21ba1f70a007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DeepSeek V3 (March 2024) model.",
                            Name = "deepseek-v3-0324",
                            Version = "3.0"
                        });
                });

            modelBuilder.Entity("QuestionService.Models.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("QuestionService.Models.AnswerByAI", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Alternatives")
                        .HasColumnType("text");

                    b.Property<string>("CodePatch")
                        .HasColumnType("text");

                    b.Property<float?>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<string>("FixStepByStep")
                        .HasColumnType("text");

                    b.Property<string>("Gotchas")
                        .HasColumnType("text");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.Property<string>("LikelyRootCause")
                        .HasColumnType("text");

                    b.Property<string>("PromptUsed")
                        .HasColumnType("text");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("RawAiResponse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserHelpfulVotes")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int?>("UserNotHelpfulVotes")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AiAnswers");
                });

            modelBuilder.Entity("QuestionService.Models.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("AnswerCount")
                        .HasColumnType("integer");

                    b.Property<string>("AskerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAcceptedAnswer")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("TagSlugs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuestionService.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = "aspire",
                            Description = "A composable, opinionated stack for building distributed apps with .NET. Provides dashboard, diagnostics, and simplified service orchestration.",
                            Name = "Aspire",
                            Slug = "aspire",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "keycloak",
                            Description = "An open-source identity and access management solution for modern applications and services. Integrates easily with OAuth2, OIDC, and SSO.",
                            Name = "Keycloak",
                            Slug = "keycloak",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "dotnet",
                            Description = "A modern, cross-platform development platform for building cloud, web, mobile, desktop, and IoT apps using C# and F#.",
                            Name = ".NET",
                            Slug = "dotnet",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "ef-core",
                            Description = "A modern object-database mapper (ORM) for .NET that supports LINQ, change tracking, and migrations for working with relational databases.",
                            Name = "Entity Framework Core",
                            Slug = "ef-core",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "wolverine",
                            Description = "A high-performance messaging and command-handling framework for .NET with built-in support for Mediator, queues, retries, and durable messaging.",
                            Name = "Wolverine",
                            Slug = "wolverine",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "postgresql",
                            Description = "A powerful, open-source object-relational database system known for reliability, feature richness, and standards compliance.",
                            Name = "PostgreSQL",
                            Slug = "postgresql",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "signalr",
                            Description = "A real-time communication library for ASP.NET that enables server-to-client messaging over WebSockets, long polling, and more.",
                            Name = "SignalR",
                            Slug = "signalr",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "nextjs",
                            Description = "A React framework for building fast, full-stack web apps with server-side rendering, routing, and static site generation.",
                            Name = "Next.js",
                            Slug = "nextjs",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "typescript",
                            Description = "A statically typed superset of JavaScript that compiles to clean JavaScript. Helps build large-scale apps with tooling support.",
                            Name = "TypeScript",
                            Slug = "typescript",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = "microservices",
                            Description = "An architectural style that structures an application as a collection of loosely coupled services that can be independently deployed and scaled.",
                            Name = "Microservices",
                            Slug = "microservices",
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("QuestionService.Models.Answer", b =>
                {
                    b.HasOne("QuestionService.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionService.Models.AnswerByAI", b =>
                {
                    b.HasOne("QuestionService.Models.Question", "Question")
                        .WithMany("AiAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionService.Models.Question", b =>
                {
                    b.Navigation("AiAnswers");

                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
